export const TRANSACTION_DEPOSIT_REQUEST = 'TRANSACTION_DEPOSIT_REQUEST'
export const TRANSACTION_DEPOSIT_SUCCESS = 'TRANSACTION_DEPOSIT_SUCCESS'
export const TRANSACTION_DEPOSIT_FAIL = 'TRANSACTION_DEPOSIT_FAIL'
export const TRANSACTION_DEPOSIT_RESET = 'TRANSACTION_DEPOSIT_RESET'

export const TRANSACTION_WITHDRAWL_REQUEST = 'TRANSACTION_WITHDRAWL_REQUEST'
export const TRANSACTION_WITHDRAWL_SUCCESS = 'TRANSACTION_WITHDRAWL_SUCCESS'
export const TRANSACTION_WITHDRWAL_FAIL = 'TRANSACTION_WITHDRWAL_FAIL'
export const TRANSACTION_WITHDRAWL_RESET = 'TRANSACTION_WITHDRAWL_RESET'

export const TRANSACTION_TRANSFER_REQUEST = 'TRANSACTION_TRANSFER_REQUEST'
export const TRANSACTION_TRANSFER_SUCCESS = 'TRANSACTION_TRANSFER_SUCCESS'
export const TRANSACTION_TRANSFER_FAIL = 'TRANSACTION_TRANSFER_FAIL'
export const TRANSACTION_TRANSFER_RESET = 'TRANSACTION_TRANSFER_RESET'

export const TRANSACTION_SALDO_REQUEST = 'TRANSACTION_SALDO_REQUEST'
export const TRANSACTION_SALDO_SUCCESS = 'TRANSACTION_SALDO_SUCCESS'
export const TRANSACTION_SALDO_FAIL = 'TRANSACTION_SALDO_FAIL'
